[customizations.installer.kickstart]
contents = """
graphical
network --bootproto=dhcp --device=link --activate --onboot=on
"""

[customizations.installer.modules]
enable = [
  "org.fedoraproject.Anaconda.Modules.Localization",
  "org.fedoraproject.Anaconda.Modules.Timezone"
]
