name: Generate and Release ISO
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: read

jobs:
  generate-iso:
    name: Generate ISO
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull image
        run: sudo podman pull ghcr.io/project-rebelos/rebel-ryzen-alpha:latest

      - name: Build ISO
        run: |
          mkdir -p output
          sudo podman run \
           --rm --privileged \
           --pull=newer \
           --security-opt label=type:unconfined_t \
           -v ./config.toml:/config.toml:ro \
           -v ./output:/output \
           -v /var/lib/containers/storage:/var/lib/containers/storage \
           quay.io/centos-bootc/bootc-image-builder:latest \
           --type anaconda-iso \
           ghcr.io/project-rebelos/rebel-ryzen-alpha:latest

      - name: Compress ISO
        run: zstd -T0 ./output/bootiso/*.iso -o ./output/bootiso/rebel-ryzen-alpha.iso.zst

      - name: Create Release and Upload ISO
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: ./output/bootiso/rebel-ryzen-alpha.iso.zst
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload ISO as artifact
        uses: actions/upload-artifact@v4
        with:
          name: rebel-ryzen-alpha-iso
          path: ./output/bootiso/*
          if-no-files-found: error
          retention-days: 7
          compression-level: 0

      - name: Create Release and Upload ISO
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: ./output/bootiso/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
